FROM gcr.io/cloudshell-images/cloudshell:latest

# Install Nextflow
RUN wget -qO- https://get.nextflow.io | bash && \
    mv nextflow /usr/local/bin/

# Set Nextflow executable permissions
RUN chmod +x /usr/local/bin/nextflow

# Install build-essential for make and git
RUN apt-get update && apt-get install -y build-essential git

# Clone and install cluster-toolkit
RUN git clone https://github.com/GoogleCloudPlatform/cluster-toolkit.git /tmp/cluster-toolkit && \
    cd /tmp/cluster-toolkit && \
    make && \
    make install

# Install Apptainer dependencies and Apptainer via PPA
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:apptainer/ppa && \
    apt-get update && \
    apt-get install -y apptainer-suid

# Install noVNC and desktop environment dependencies
RUN apt-get update && apt-get install -y \
    novnc \
    python3-websockify \
    python3-numpy \
    tightvncserver lxde && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# --- noVNC startup script ---
COPY start-desktop.sh /usr/local/bin/startup-desktop.sh 

RUN chmod a+rwx /usr/local/bin/startup-desktop.sh

# Expose noVNC port:
EXPOSE 6080
