apiVersion: v1
kind: PersistentVolume
metadata:
  name: openfold-pv
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /openfold_root
    server: 10.x.x.x # <--- CLIENT MUST REPLACE WITH FILESTORE IP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openfold-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 4Ti
  volumeName: openfold-pv
